# This configuration is applied on top of the root .eslintrc.yml, which is platform agnostic (e.g. Node.js vs. React).

# This is for quickly ignoring all TypeScript rules while we start typing our packages.
# In the long run, we should remove this configuration.

rules:
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/explicit-member-accessibility": off
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/indent": off
  "@typescript-eslint/interface-name-prefix": off
  "@typescript-eslint/no-explicit-any": off
