const POST_ACTIVITY = 'DIRECT_LINE/POST_ACTIVITY';
export const POST_ACTIVITY_FULFILLED = `${POST_ACTIVITY}_FULFILLED`;
export const POST_ACTIVITY_PENDING = `${POST_ACTIVITY}_PENDING`;
export const POST_ACTIVITY_REJECTED = `${POST_ACTIVITY}_REJECTED`;

export { POST_ACTIVITY };
