# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI/CD dev release

on:
  push:
    branches:
      - master
      - fix-a11y-post-4.9.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run npx version-from-git --no-git-tag-version
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        run: npx version-from-git --no-git-tag-version

      - run: npm ci

      - run: npm run bootstrap -- --ignore=playground

      - name: Propagate versions
        run: |
          node_modules/.bin/lerna version --force-publish --no-git-tag-version --no-push --yes `cat package.json | jq -r .version`

      - run: npm run build --if-present -- --ignore=playground

      # - run: npm test

      - name: Run npm pack bundle
        run: |
          cd packages/bundle
          npm pack

      - name: Run npm pack component
        run: |
          cd packages/component
          npm pack

      - name: Run npm pack core
        run: |
          cd packages/core
          npm pack

      - name: Run npm pack directlinespeech
        run: |
          cd packages/directlinespeech
          npm pack

      - name: Upload bundle
        uses: actions/upload-artifact@v2
        if: ${{ matrix.node-version == '14.x' }}
        with:
          name: bundle
          path: 'packages/bundle/dist/**/*'

      - name: Upload npm-tarball
        uses: actions/upload-artifact@v2
        if: ${{ matrix.node-version == '14.x' }}
        with:
          name: npm-tarball
          path: 'packages/*/*.tgz'

  github-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Read variables
        id: variables
        run: |
          echo "::set-output name=tag_name::dev-$(git rev-parse --abbrev-ref HEAD)"

      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Create a tag
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git tag -f ${{ steps.variables.outputs.tag_name }}
          git push --force origin -f ${{ steps.variables.outputs.tag_name }}

  github-release:
    needs: github-tag
    runs-on: ubuntu-latest

    steps:
      - name: Download npm-tarball
        uses: actions/download-artifact@v2
        with:
          name: npm-tarball

      - name: Read variables
        id: variables
        run: |
          echo "::set-output name=version::$(tar xOf botframework-webchat-4.*.tgz package/package.json | jq -r '.version')"
          echo "::set-output name=date::$(date +%Y-%m-%d)"
          echo "::set-output name=build_time::$(node -p "new Date().toISOString()")"
          echo "::set-output name=branch_name::$(git rev-parse --abbrev-ref HEAD)"
          echo "::set-output name=tag_name::dev-$(git rev-parse --abbrev-ref HEAD)"
          echo "::set-output name=commitish::$(git rev-parse --short --verify HEAD)"

      - name: Create a release
        uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          release_name: '[${{ steps.variables.outputs.tag_name }}] - ${{ steps.variables.outputs.date }}'
          tag_name: ${{ steps.variables.outputs.tag_name }}
          body: |
            > Tarballs can be found in this workflow, https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.

            <table>
              <thead>
                <tr>
                  <th>Build time</th>
                  <th>Workflow ID</th>
                  <th>Source version</th>
                  <th>Branch</th>
                  <th>Package version</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>${{ steps.variables.outputs.build_time }}</td>
                  <td>
                    <code>
                      <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">${{ github.run_id }}</a>
                    </code>
                  </td>
                  <td>
                    <code>
                      <a href="https://github.com/${{ github.repository }}/commit/${{ steps.variables.outputs.commitish }}">${{ steps.variables.outputs.commitish }}</a>
                    </code>
                  </td>
                  <td>
                    <code>
                      <a href="https://github.com/${{ github.repository }}/tree/${{ steps.variables.outputs.branch_name }}">${{ steps.variables.outputs.branch_name }}</a>
                    </code>
                  </td>
                  <td>
                    <code>${{ steps.variables.outputs.version }}</code>
                  </td>
                </tr>
              </tbody>
            </table>

            ```
            <script
              crossorigin="anonymous"
              src="https://github.com/${{ github.repository }}/releases/download/${{ steps.variables.outputs.tag_name }}/webchat.js"
            ></script>

            <script
              crossorigin="anonymous"
              src="https://github.com/${{ github.repository }}/releases/download/${{ steps.variables.outputs.tag_name }}/webchat-es5.js"
            ></script>

            <script
              crossorigin="anonymous"
              src="https://github.com/${{ github.repository }}/releases/download/${{ steps.variables.outputs.tag_name }}/webchat-minimal.js"
            ></script>
            ```

      - name: Upload webchat.js to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: packages/bundle/dist/webchat.js
          asset_name: webchat.js
          asset_content_type: text/javascript

      - name: Upload webchat-es5.js to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: packages/bundle/dist/webchat-es5.js
          asset_name: webchat-es5.js
          asset_content_type: text/javascript

      - name: Upload webchat-minimal.js to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: packages/bundle/dist/webchat-minimal.js
          asset_name: webchat-minimal.js
          asset_content_type: text/javascript

      - name: Upload stats.json to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: packages/bundle/dist/stats.json
          asset_name: stats.json
          asset_content_type: application/json
